// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcquireGame(arg1, arg2, arg3) {
  return window['go']['rift']['App']['AcquireGame'](arg1, arg2, arg3);
}

export function ActivateGameMode(arg1) {
  return window['go']['rift']['App']['ActivateGameMode'](arg1);
}

export function AddGameToLibrary(arg1, arg2) {
  return window['go']['rift']['App']['AddGameToLibrary'](arg1, arg2);
}

export function AuthDir() {
  return window['go']['rift']['App']['AuthDir']();
}

export function CalculateHardwareOptimizations(arg1, arg2) {
  return window['go']['rift']['App']['CalculateHardwareOptimizations'](arg1, arg2);
}

export function CancelDownload(arg1) {
  return window['go']['rift']['App']['CancelDownload'](arg1);
}

export function CheckEnginesStatus() {
  return window['go']['rift']['App']['CheckEnginesStatus']();
}

export function CheckForUpdates() {
  return window['go']['rift']['App']['CheckForUpdates']();
}

export function CheckRosettaInstalled() {
  return window['go']['rift']['App']['CheckRosettaInstalled']();
}

export function CheckSystemDependencies() {
  return window['go']['rift']['App']['CheckSystemDependencies']();
}

export function ConfigureGamePrefix(arg1) {
  return window['go']['rift']['App']['ConfigureGamePrefix'](arg1);
}

export function DeactivateGameMode() {
  return window['go']['rift']['App']['DeactivateGameMode']();
}

export function DownloadAndApplyUpdate(arg1) {
  return window['go']['rift']['App']['DownloadAndApplyUpdate'](arg1);
}

export function DownloadEpicWithTags(arg1, arg2, arg3) {
  return window['go']['rift']['App']['DownloadEpicWithTags'](arg1, arg2, arg3);
}

export function DownloadGame(arg1) {
  return window['go']['rift']['App']['DownloadGame'](arg1);
}

export function EnginesDir() {
  return window['go']['rift']['App']['EnginesDir']();
}

export function EnsureBaseDirectories() {
  return window['go']['rift']['App']['EnsureBaseDirectories']();
}

export function EnsureEssentialRuntimes(arg1, arg2) {
  return window['go']['rift']['App']['EnsureEssentialRuntimes'](arg1, arg2);
}

export function EnsureRosetta() {
  return window['go']['rift']['App']['EnsureRosetta']();
}

export function ExecuteSetupRouter(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['rift']['App']['ExecuteSetupRouter'](arg1, arg2, arg3, arg4, arg5);
}

export function ExecuteTranslation(arg1, arg2, arg3) {
  return window['go']['rift']['App']['ExecuteTranslation'](arg1, arg2, arg3);
}

export function FlushPendingTelemetry() {
  return window['go']['rift']['App']['FlushPendingTelemetry']();
}

export function ForceQuitAll() {
  return window['go']['rift']['App']['ForceQuitAll']();
}

export function ForceQuitGame(arg1) {
  return window['go']['rift']['App']['ForceQuitGame'](arg1);
}

export function GamesDir() {
  return window['go']['rift']['App']['GamesDir']();
}

export function GetActiveDownloads() {
  return window['go']['rift']['App']['GetActiveDownloads']();
}

export function GetAppBuildInfo() {
  return window['go']['rift']['App']['GetAppBuildInfo']();
}

export function GetAppVersion() {
  return window['go']['rift']['App']['GetAppVersion']();
}

export function GetAuthStatus() {
  return window['go']['rift']['App']['GetAuthStatus']();
}

export function GetCoverArtMap(arg1) {
  return window['go']['rift']['App']['GetCoverArtMap'](arg1);
}

export function GetEpicDownloadPacks(arg1) {
  return window['go']['rift']['App']['GetEpicDownloadPacks'](arg1);
}

export function GetFullConfig() {
  return window['go']['rift']['App']['GetFullConfig']();
}

export function GetGameExecutables(arg1) {
  return window['go']['rift']['App']['GetGameExecutables'](arg1);
}

export function GetGameRuntimeConfig(arg1) {
  return window['go']['rift']['App']['GetGameRuntimeConfig'](arg1);
}

export function GetGamesDir() {
  return window['go']['rift']['App']['GetGamesDir']();
}

export function GetLastSessionCoreInfo() {
  return window['go']['rift']['App']['GetLastSessionCoreInfo']();
}

export function GetLastSessionSummary() {
  return window['go']['rift']['App']['GetLastSessionSummary']();
}

export function GetLastSessionTelemetry() {
  return window['go']['rift']['App']['GetLastSessionTelemetry']();
}

export function GetPlaytimeStats() {
  return window['go']['rift']['App']['GetPlaytimeStats']();
}

export function GetSanitizedLogs() {
  return window['go']['rift']['App']['GetSanitizedLogs']();
}

export function GetStorageStats() {
  return window['go']['rift']['App']['GetStorageStats']();
}

export function GetSystemSpecs() {
  return window['go']['rift']['App']['GetSystemSpecs']();
}

export function GetUserProfileData() {
  return window['go']['rift']['App']['GetUserProfileData']();
}

export function HasActiveDownloads() {
  return window['go']['rift']['App']['HasActiveDownloads']();
}

export function ImportGameFromFolder() {
  return window['go']['rift']['App']['ImportGameFromFolder']();
}

export function ImportLocalGame(arg1, arg2, arg3, arg4) {
  return window['go']['rift']['App']['ImportLocalGame'](arg1, arg2, arg3, arg4);
}

export function InjectEngineDLLs(arg1, arg2) {
  return window['go']['rift']['App']['InjectEngineDLLs'](arg1, arg2);
}

export function InstallEngine(arg1) {
  return window['go']['rift']['App']['InstallEngine'](arg1);
}

export function InstallSystemDependencies() {
  return window['go']['rift']['App']['InstallSystemDependencies']();
}

export function IsGameMacNative(arg1, arg2, arg3, arg4) {
  return window['go']['rift']['App']['IsGameMacNative'](arg1, arg2, arg3, arg4);
}

export function IsLoggedIn() {
  return window['go']['rift']['App']['IsLoggedIn']();
}

export function IsStoreReady(arg1) {
  return window['go']['rift']['App']['IsStoreReady'](arg1);
}

export function KillSteamBrowser() {
  return window['go']['rift']['App']['KillSteamBrowser']();
}

export function LaunchEpicNative(arg1, arg2, arg3) {
  return window['go']['rift']['App']['LaunchEpicNative'](arg1, arg2, arg3);
}

export function LaunchEpicTranslated(arg1, arg2, arg3, arg4) {
  return window['go']['rift']['App']['LaunchEpicTranslated'](arg1, arg2, arg3, arg4);
}

export function LaunchSteamNative(arg1, arg2, arg3) {
  return window['go']['rift']['App']['LaunchSteamNative'](arg1, arg2, arg3);
}

export function LaunchSteamTranslated(arg1, arg2, arg3, arg4) {
  return window['go']['rift']['App']['LaunchSteamTranslated'](arg1, arg2, arg3, arg4);
}

export function LocateAndImportGame(arg1, arg2, arg3) {
  return window['go']['rift']['App']['LocateAndImportGame'](arg1, arg2, arg3);
}

export function LogGameActivity() {
  return window['go']['rift']['App']['LogGameActivity']();
}

export function LogMessage(arg1, arg2) {
  return window['go']['rift']['App']['LogMessage'](arg1, arg2);
}

export function LogoutEpic() {
  return window['go']['rift']['App']['LogoutEpic']();
}

export function LogoutSteam() {
  return window['go']['rift']['App']['LogoutSteam']();
}

export function MonitorGame(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['rift']['App']['MonitorGame'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function OpenEpicStore() {
  return window['go']['rift']['App']['OpenEpicStore']();
}

export function OpenSteamBrowser() {
  return window['go']['rift']['App']['OpenSteamBrowser']();
}

export function OpenSteamChat() {
  return window['go']['rift']['App']['OpenSteamChat']();
}

export function OpenSteamGame(arg1) {
  return window['go']['rift']['App']['OpenSteamGame'](arg1);
}

export function PlayGame(arg1, arg2, arg3) {
  return window['go']['rift']['App']['PlayGame'](arg1, arg2, arg3);
}

export function PurgeCache() {
  return window['go']['rift']['App']['PurgeCache']();
}

export function RefreshSteamAppList() {
  return window['go']['rift']['App']['RefreshSteamAppList']();
}

export function RemoveFromLibrary(arg1) {
  return window['go']['rift']['App']['RemoveFromLibrary'](arg1);
}

export function ResolveGameDir(arg1) {
  return window['go']['rift']['App']['ResolveGameDir'](arg1);
}

export function RestoreWindow() {
  return window['go']['rift']['App']['RestoreWindow']();
}

export function RiftDir() {
  return window['go']['rift']['App']['RiftDir']();
}

export function SaveFullConfig(arg1) {
  return window['go']['rift']['App']['SaveFullConfig'](arg1);
}

export function SaveGameRuntimeConfig(arg1, arg2) {
  return window['go']['rift']['App']['SaveGameRuntimeConfig'](arg1, arg2);
}

export function ScanMacForInstalledGames() {
  return window['go']['rift']['App']['ScanMacForInstalledGames']();
}

export function SearchSteamAppList(arg1) {
  return window['go']['rift']['App']['SearchSteamAppList'](arg1);
}

export function SelectGameExecutable(arg1, arg2) {
  return window['go']['rift']['App']['SelectGameExecutable'](arg1, arg2);
}

export function SelectLibraryFolder() {
  return window['go']['rift']['App']['SelectLibraryFolder']();
}

export function SetGameExecutable(arg1, arg2) {
  return window['go']['rift']['App']['SetGameExecutable'](arg1, arg2);
}

export function SetupEpicNative(arg1, arg2, arg3) {
  return window['go']['rift']['App']['SetupEpicNative'](arg1, arg2, arg3);
}

export function SetupEpicStore() {
  return window['go']['rift']['App']['SetupEpicStore']();
}

export function SetupEpicTranslated(arg1, arg2, arg3) {
  return window['go']['rift']['App']['SetupEpicTranslated'](arg1, arg2, arg3);
}

export function SetupSteamNative(arg1, arg2, arg3) {
  return window['go']['rift']['App']['SetupSteamNative'](arg1, arg2, arg3);
}

export function SetupSteamTranslated(arg1, arg2, arg3) {
  return window['go']['rift']['App']['SetupSteamTranslated'](arg1, arg2, arg3);
}

export function StartEpicAuth() {
  return window['go']['rift']['App']['StartEpicAuth']();
}

export function StartSteamAuth(arg1, arg2, arg3) {
  return window['go']['rift']['App']['StartSteamAuth'](arg1, arg2, arg3);
}

export function SteamCMDDir() {
  return window['go']['rift']['App']['SteamCMDDir']();
}

export function StopActiveDownloadsOnExit() {
  return window['go']['rift']['App']['StopActiveDownloadsOnExit']();
}

export function StoresDir() {
  return window['go']['rift']['App']['StoresDir']();
}

export function SupabaseGetUser() {
  return window['go']['rift']['App']['SupabaseGetUser']();
}

export function SupabaseResetPasswordForEmail(arg1) {
  return window['go']['rift']['App']['SupabaseResetPasswordForEmail'](arg1);
}

export function SupabaseSignIn(arg1, arg2) {
  return window['go']['rift']['App']['SupabaseSignIn'](arg1, arg2);
}

export function SupabaseSignOut() {
  return window['go']['rift']['App']['SupabaseSignOut']();
}

export function SupabaseSignUp(arg1, arg2, arg3) {
  return window['go']['rift']['App']['SupabaseSignUp'](arg1, arg2, arg3);
}

export function SupabaseUpdatePassword(arg1) {
  return window['go']['rift']['App']['SupabaseUpdatePassword'](arg1);
}

export function SupabaseVerifyResetCodeAndSetPassword(arg1, arg2, arg3) {
  return window['go']['rift']['App']['SupabaseVerifyResetCodeAndSetPassword'](arg1, arg2, arg3);
}

export function SyncCloudPlaytimeOnLogin() {
  return window['go']['rift']['App']['SyncCloudPlaytimeOnLogin']();
}

export function SyncLibrary() {
  return window['go']['rift']['App']['SyncLibrary']();
}

export function SyncUserPlaytime(arg1, arg2, arg3) {
  return window['go']['rift']['App']['SyncUserPlaytime'](arg1, arg2, arg3);
}

export function TrackUserEvent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['rift']['App']['TrackUserEvent'](arg1, arg2, arg3, arg4, arg5);
}

export function UninstallGame(arg1) {
  return window['go']['rift']['App']['UninstallGame'](arg1);
}

export function UnlockAchievement(arg1) {
  return window['go']['rift']['App']['UnlockAchievement'](arg1);
}

export function UserAuthDir() {
  return window['go']['rift']['App']['UserAuthDir']();
}

export function UserDir() {
  return window['go']['rift']['App']['UserDir']();
}
