// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rift} from '../models';
import {runners} from '../models';
import {types} from '../models';
import {adapters} from '../models';
import {exec} from '../models';

export function AcquireGame(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ActivateGameMode(arg1:number):Promise<void>;

export function AddGameToLibrary(arg1:string,arg2:string):Promise<Record<string, any>>;

export function AuthDir():Promise<string>;

export function CalculateHardwareOptimizations(arg1:string,arg2:string):Promise<void>;

export function CancelDownload(arg1:string):Promise<string>;

export function CheckEnginesStatus():Promise<string>;

export function CheckForUpdates():Promise<rift.UpdateInfo>;

export function CheckRosettaInstalled():Promise<boolean>;

export function CheckSystemDependencies():Promise<boolean>;

export function ConfigureGamePrefix(arg1:string):Promise<string>;

export function DeactivateGameMode():Promise<void>;

export function DownloadAndApplyUpdate(arg1:string):Promise<void>;

export function DownloadEpicWithTags(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function DownloadGame(arg1:string):Promise<string>;

export function EnginesDir():Promise<string>;

export function EnsureBaseDirectories():Promise<void>;

export function EnsureEssentialRuntimes(arg1:string,arg2:string):Promise<void>;

export function EnsureRosetta():Promise<boolean>;

export function ExecuteSetupRouter(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function ExecuteTranslation(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FlushPendingTelemetry():Promise<void>;

export function ForceQuitAll():Promise<string>;

export function ForceQuitGame(arg1:string):Promise<string>;

export function GamesDir():Promise<string>;

export function GetActiveDownloads():Promise<Array<rift.ActiveDownloadRecord>>;

export function GetAppBuildInfo():Promise<Record<string, string>>;

export function GetAppVersion():Promise<string>;

export function GetAuthStatus():Promise<rift.AuthStatus>;

export function GetCoverArtMap(arg1:string):Promise<string>;

export function GetEpicDownloadPacks(arg1:string):Promise<Array<runners.SelectivePack>>;

export function GetFullConfig():Promise<rift.AppConfig>;

export function GetGameExecutables(arg1:string):Promise<Array<rift.GameExecutableInfo>>;

export function GetGameRuntimeConfig(arg1:string):Promise<types.RuntimeConfig>;

export function GetGamesDir():Promise<string>;

export function GetLastSessionCoreInfo():Promise<string>;

export function GetLastSessionSummary():Promise<string>;

export function GetLastSessionTelemetry():Promise<string>;

export function GetPlaytimeStats():Promise<string>;

export function GetSanitizedLogs():Promise<string>;

export function GetStorageStats():Promise<rift.StorageStats>;

export function GetSystemSpecs():Promise<Record<string, any>>;

export function GetUserProfileData():Promise<string>;

export function HasActiveDownloads():Promise<boolean>;

export function ImportGameFromFolder():Promise<adapters.RIFTUIProfile>;

export function ImportLocalGame(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function InjectEngineDLLs(arg1:string,arg2:string):Promise<void>;

export function InstallEngine(arg1:string):Promise<string>;

export function InstallSystemDependencies():Promise<string>;

export function IsGameMacNative(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function IsLoggedIn():Promise<boolean>;

export function IsStoreReady(arg1:string):Promise<boolean>;

export function KillSteamBrowser():Promise<string>;

export function LaunchEpicNative(arg1:string,arg2:string,arg3:string):Promise<string>;

export function LaunchEpicTranslated(arg1:string,arg2:string,arg3:string,arg4:types.RuntimeConfig):Promise<string>;

export function LaunchSteamNative(arg1:string,arg2:string,arg3:string):Promise<string>;

export function LaunchSteamTranslated(arg1:string,arg2:string,arg3:string,arg4:types.RuntimeConfig):Promise<string>;

export function LocateAndImportGame(arg1:string,arg2:string,arg3:string):Promise<string>;

export function LogGameActivity():Promise<string>;

export function LogMessage(arg1:string,arg2:string):Promise<void>;

export function LogoutEpic():Promise<boolean>;

export function LogoutSteam():Promise<string>;

export function MonitorGame(arg1:string,arg2:string,arg3:string,arg4:string,arg5:exec.Cmd,arg6:any,arg7:any,arg8:number):Promise<void>;

export function OpenEpicStore():Promise<string>;

export function OpenSteamBrowser():Promise<string>;

export function OpenSteamChat():Promise<string>;

export function OpenSteamGame(arg1:string):Promise<string>;

export function PlayGame(arg1:string,arg2:string,arg3:string):Promise<string>;

export function PurgeCache():Promise<boolean>;

export function RefreshSteamAppList():Promise<string>;

export function RemoveFromLibrary(arg1:string):Promise<Record<string, any>>;

export function ResolveGameDir(arg1:string):Promise<string>;

export function RestoreWindow():Promise<void>;

export function RiftDir():Promise<string>;

export function SaveFullConfig(arg1:rift.AppConfig):Promise<void>;

export function SaveGameRuntimeConfig(arg1:string,arg2:types.RuntimeConfig):Promise<void>;

export function ScanMacForInstalledGames():Promise<Array<adapters.RIFTUIProfile>>;

export function SearchSteamAppList(arg1:string):Promise<string>;

export function SelectGameExecutable(arg1:string,arg2:string):Promise<string>;

export function SelectLibraryFolder():Promise<string>;

export function SetGameExecutable(arg1:string,arg2:string):Promise<void>;

export function SetupEpicNative(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetupEpicStore():Promise<string>;

export function SetupEpicTranslated(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetupSteamNative(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetupSteamTranslated(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartEpicAuth():Promise<string>;

export function StartSteamAuth(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function SteamCMDDir():Promise<string>;

export function StopActiveDownloadsOnExit():Promise<void>;

export function StoresDir():Promise<string>;

export function SupabaseGetUser():Promise<string>;

export function SupabaseResetPasswordForEmail(arg1:string):Promise<string>;

export function SupabaseSignIn(arg1:string,arg2:string):Promise<string>;

export function SupabaseSignOut():Promise<string>;

export function SupabaseSignUp(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SupabaseUpdatePassword(arg1:string):Promise<string>;

export function SupabaseVerifyResetCodeAndSetPassword(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SyncCloudPlaytimeOnLogin():Promise<void>;

export function SyncLibrary():Promise<Array<adapters.RIFTUIProfile>>;

export function SyncUserPlaytime(arg1:string,arg2:string,arg3:number):Promise<void>;

export function TrackUserEvent(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<string, any>):Promise<void>;

export function UninstallGame(arg1:string):Promise<string>;

export function UnlockAchievement(arg1:string):Promise<string>;

export function UserAuthDir():Promise<string>;

export function UserDir():Promise<string>;
